# Site
name: "Foreningen for Danske Cyber Alumner"
title: "FDCA Blog"
description: ""
logo: 'assets/images/logo/full_smalltext_transparent_pink.png'
favicon: 'assets/images/logo/stamp_transparent_pink.png'
url: https://fdca.dk
disqus: 'FDCA Blog'
include: ["_pages"]
permalink: /:title/
email: info@fdca.dk

# Authors
authors:
  at:
    name: Andreas Thorlund
    display_name: Andreas
    avatar: 'assets/images/people/andreas-thorlund.jpg'
    email: at@fdca.dk
    web: https://www.linkedin.com/in/andreas-thorlund-a8103b21b/
    linkedin: https://www.linkedin.com/in/andreas-thorlund-a8103b21b/
    description: "Andreas er hovedansvarlig for sporet vedrørende samfundspåvirkning. Derudover så er han hovedansvarlig for foreningens sociale medier. "
  ch:
    name: Christian Henriksen
    display_name: Christian
    avatar: 'assets/images/people/christian-henriksen.jpg'
    email: ch@fdca.dk
    web: https://www.linkedin.com/in/cbhen/
    linkedin: https://www.linkedin.com/in/cbhen/
    description: "Christian bidrager til sporet omkring samfundspåvirkning. Han er også hovedansvarlig for kontakt med samarbejdspartnere og støttemedlemmer. "  
  kh:
    name: Kasper Hjortborg Kristiansen  
    display_name: Kasper
    avatar: 'assets/images/people/kasper-hjortborg.jpg'
    email: kh@fdca.dk
    web: https://www.linkedin.com/in/kasper-hjortborg/
    linkedin: https://www.linkedin.com/in/kasper-hjortborg/
    description: "Kasper er ansvarlig for sporet vedrørende skabelse af et relationelt netværk gennem forskellige arrangementer. "     
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page/:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
